version: '3.9'

services:
  db:
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=email-notification
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres